name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true

      - name: Copy files to docs
        run: |
          mkdir -p docs
          cp apps/web/index.html docs/index.html
          cp apps/web/gmanhole_map.html docs/gmanhole_map.html
          # Nearby page (shortened filename)
          cp apps/web/nearby_manholes.html docs/nearby.html
          # Static assets (CSS etc.)
          rm -rf docs/assets
          cp -r apps/web/assets docs/assets
          # Data files
          cp apps/scraper/pokefuta.ndjson docs/pokefuta.ndjson
          cp apps/web/assets/gmanhole.ndjson docs/gmanhole.ndjson || true
          # Backward compatibility redirect for old URL
          echo '<!doctype html><meta http-equiv="refresh" content="0; url=./nearby.html">' > docs/nearby_manholes.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4