name: Build & Deploy Pokefuta Pages (Artifact)

on:
  workflow_dispatch:
  schedule:
    - cron: '30 10 * * *' # After daily dataset update

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt beautifulsoup4 requests

      - name: Prepare dist directory (dataset + site)
        run: |
          set -e
          mkdir -p dist/assets
          echo "[dist] Building public dataset (active only)"
          python apps/scraper/update_pokefuta.py \
            --scan-max 0 \
            --out /dev/null \
            --copy-to dist/pokefuta.ndjson \
            --log-level WARN || echo "Updater exited (scan-max=0 path)";
          echo "[dist] Copy HTML sources"
          cp apps/web/pokefuta_map.html dist/index.html
          cp apps/web/nearby.html dist/nearby.html
          echo '<!doctype html><meta http-equiv="refresh" content="0; url=./nearby.html">' > dist/nearby_manholes.html
          echo "[dist] Copy assets (CSS + images)"
          cp -r apps/web/assets/* dist/assets/ || true
          echo "[dist] Copy manhole icon → assets"
          cp dataset/manhole_icon.png dist/assets/manhole_icon.png || true
          echo "[dist] Ensure pokefuta icons live under assets (favicon & marker variants)"
          cp apps/web/assets/pokefuta_icon_32.png dist/assets/pokefuta_icon_32.png || true
          cp apps/web/assets/pokefuta_icon_24.png dist/assets/pokefuta_icon_24.png || true
          cp apps/web/assets/pokefuta_icon_clear32.png dist/assets/pokefuta_icon_clear32.png || true
          echo "[dist] Verify critical assets exist";
          for f in dist/assets/manhole_icon.png dist/assets/pokefuta_icon_32.png; do
            if [ ! -f "$f" ]; then echo "[WARN] Missing asset: $f"; fi; done
          echo "[dist] Listing dist contents"; find dist -maxdepth 2 -type f -print | sort

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
